In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pandas_datareader.data as web
import datetime as dt

In [9]:
data = pd.DataFrame()
tickers = ['EWA', 'EWZ', 'EWC', 'FXI', 'EWQ', 'EWG', 'EWH', 'EWI', 'EWJ', 'EWY',
           'EWN', 'EWS', 'EZA', 'EWP', 'EWD', 'EWL', 'EWT', 'EWU', 'IVV']
q = len(tickers)
records = 0
for i in tickers:
    tmp = web.DataReader(i, 'yahoo', '1/3/2005', '12/31/2019')   #1/3 is the first business day of 2005
    data[i] = tmp['Close']

data.head()

EWA        EWZ        EWC        FXI        EWQ        EWG  \
Date                                                                           
2005-01-03  16.469999  21.660000  17.120001  18.383333  23.940001  18.549999   
2005-01-04  16.180000  20.730000  16.620001  17.876667  23.400000  18.180000   
2005-01-05  16.240000  20.549999  16.400000  17.469999  23.430000  18.190001   
2005-01-06  16.270000  20.370001  16.309999  17.490000  23.370001  18.200001   
2005-01-07  16.250000  20.650000  16.270000  17.333334  23.299999  18.080000   

              EWH        EWI        EWJ        EWY        EWN    EWS  \
Date                                                                   
2005-01-03  12.00  50.919998  43.160000  28.850000  18.440001  14.14   
2005-01-04  11.71  49.759998  42.439999  28.059999  18.170000  13.90   
2005-01-05  11.45  50.020000  42.400002  28.250000  18.049999  14.16   
2005-01-06  11.56  49.980000  42.400002  27.780001  18.100000  14.42   
2005-01-07  11.44  49.459999  42.160000  27.700001  17.900000  14.22   

                  EZA        EWP        EWD        EWL        EWT        EWU  \
Date                                                                           
2005-01-03  40.150002  35.119999  21.150000  17.190001  23.740000  35.959999   
2005-01-04  38.654999  34.450001  20.620001  16.650000  23.200001  35.299999   
2005-01-05  37.605000  34.259998  20.610001  16.650000  23.100000  35.320000   
2005-01-06  36.500000  34.419998  20.650000  16.670000  23.080000  35.299999   
2005-01-07  36.695000  33.680000  20.400000  16.350000  22.900000  35.340000   

                   IVV  
Date                    
2005-01-03  120.459999  
2005-01-04  119.010002  
2005-01-05  118.290001  
2005-01-06  118.769997  
2005-01-07  118.550003

In [10]:
data.to_csv("data_close.csv")

In [11]:
data = pd.DataFrame()
tickers = ['EWA', 'EWZ', 'EWC', 'FXI', 'EWQ', 'EWG', 'EWH', 'EWI', 'EWJ', 'EWY',
           'EWN', 'EWS', 'EZA', 'EWP', 'EWD', 'EWL', 'EWT', 'EWU', 'IVV']
q = len(tickers)
records = 0
for i in tickers:
    tmp = web.DataReader(i, 'yahoo', '1/3/2005', '12/31/2019')   #1/3 is the first business day of 2005
    data[i] = tmp['Adj Close']

data.head()

EWA        EWZ        EWC        FXI        EWQ        EWG  \
Date                                                                          
2005-01-03  8.217886  14.126711  12.931461  13.237745  16.154015  13.303169   
2005-01-04  8.073186  13.520161  12.553794  12.872897  15.789632  13.037824   
2005-01-05  8.103125  13.402760  12.387615  12.580059  15.809880  13.044994   
2005-01-06  8.118093  13.285370  12.319633  12.594460  15.769397  13.052168   
2005-01-07  8.108113  13.467980  12.289425  12.481648  15.722158  12.966111   

                 EWH        EWI        EWJ        EWY        EWN       EWS  \
Date                                                                         
2005-01-03  7.709301  31.728643  34.990158  23.648851  12.649429  7.995531   
2005-01-04  7.522993  31.005836  34.406452  23.001278  12.464212  7.859820   
2005-01-05  7.355958  31.167849  34.374020  23.157021  12.381896  8.006838   
2005-01-06  7.426626  31.142916  34.374020  22.771757  12.416193  8.153857   
2005-01-07  7.349532  30.818907  34.179440  22.706182  12.278999  8.040765   

                  EZA        EWP        EWD        EWL        EWT        EWU  \
Date                                                                           
2005-01-03  23.410761  19.021193  12.767601  12.915568  15.704612  20.224211   
2005-01-04  22.539045  18.658321  12.447660  12.509844  15.347388  19.853024   
2005-01-05  21.926809  18.555410  12.441620  12.509844  15.281234  19.864275   
2005-01-06  21.282505  18.642071  12.465767  12.524873  15.268003  19.853024   
2005-01-07  21.396206  18.241280  12.314852  12.284440  15.148928  19.875515   

                  IVV  
Date                   
2005-01-03  88.355942  
2005-01-04  87.292419  
2005-01-05  86.764305  
2005-01-06  87.116364  
2005-01-07  86.954994

In [12]:
data.to_csv("data_all.csv")

In [10]:
type(data["2005-1":"2005-3"])

pandas.core.frame.DataFrame

In [4]:
high = pd.DataFrame()
tickers = ['EWA', 'EWZ', 'EWC', 'FXI', 'EWQ', 'EWG', 'EWH', 'EWI', 'EWJ', 'EWY',
           'EWN', 'EWS', 'EZA', 'EWP', 'EWD', 'EWL', 'EWT', 'EWU', 'IVV']
q = len(tickers)
records = 0
for i in tickers:
    tmp = web.DataReader(i, 'yahoo', '1/3/2005', '12/31/2019')   #1/3 is the first business day of 2005
    high[i] = tmp['High']

high.head()

EWA        EWZ        EWC        FXI        EWQ        EWG  \
Date                                                                           
2005-01-03  16.660000  22.360001  17.200001  18.516666  24.120001  18.639999   
2005-01-04  16.590000  21.709999  16.930000  18.280001  23.750000  18.480000   
2005-01-05  16.320000  21.000000  16.590000  17.666666  23.440001  18.240000   
2005-01-06  16.299999  20.610001  16.420000  17.500000  23.500000  18.250000   
2005-01-07  16.469999  20.820000  16.520000  17.476667  23.629999  18.330000   

              EWH        EWI        EWJ        EWY        EWN    EWS  \
Date                                                                   
2005-01-03  12.16  51.279999  43.680000  29.200001  18.549999  14.34   
2005-01-04  11.96  50.700001  43.200001  28.850000  18.400000  14.20   
2005-01-05  11.62  50.400002  42.639999  28.650000  18.250000  14.22   
2005-01-06  11.62  50.099998  42.639999  28.049999  18.150000  14.44   
2005-01-07  11.55  50.180000  42.759998  28.010000  18.299999  14.40   

                  EZA        EWP        EWD        EWL        EWT        EWU  \
Date                                                                           
2005-01-03  40.275002  35.450001  21.250000  17.270000  24.299999  36.240002   
2005-01-04  39.349998  35.119999  21.200001  17.090000  23.700001  35.799999   
2005-01-05  37.924999  34.480000  20.700001  16.799999  23.299999  35.500000   
2005-01-06  36.744999  34.439999  20.660000  16.760000  23.200001  35.380001   
2005-01-07  36.750000  34.450001  20.680000  16.680000  23.160000  35.740002   

                   IVV  
Date                    
2005-01-03  121.900002  
2005-01-04  120.669998  
2005-01-05  119.379997  
2005-01-06  119.260002  
2005-01-07  119.339996

In [5]:
high.tail()

EWA        EWZ        EWC        FXI        EWQ        EWG  \
Date                                                                           
2019-12-24  22.670000  46.759998  29.680000  43.169998  32.470001  29.350000   
2019-12-26  22.790001  47.689999  29.850000  43.570000  32.610001  29.430000   
2019-12-27  22.910000  47.599998  29.910000  43.860001  32.790001  29.620001   
2019-12-30  22.889999  47.700001  29.860001  43.919998  32.750000  29.480000   
2019-12-31  22.660000  47.470001  29.900000  43.700001  32.730000  29.430000   

                  EWH        EWI        EWJ        EWY        EWN        EWS  \
Date                                                                           
2019-12-24  24.100000  29.650000  59.619999  61.250000  33.570000  23.990000   
2019-12-26  24.180000  29.740000  59.709999  61.650002  33.759998  24.049999   
2019-12-27  24.309999  29.730000  59.790001  62.680000  33.919998  24.049999   
2019-12-30  24.440001  29.620001  59.549999  62.630001  33.930000  24.090000   
2019-12-31  24.360001  29.500000  59.259998  62.320000  33.860001  24.160000   

                  EZA        EWP        EWD        EWL        EWT        EWU  \
Date                                                                           
2019-12-24  48.919998  28.820000  33.169998  40.470001  40.930000  33.750000   
2019-12-26  49.299999  28.950001  33.299999  40.599998  41.160000  33.880001   
2019-12-27  49.500000  29.120001  33.490002  40.830002  41.340000  34.139999   
2019-12-30  49.410000  29.110001  33.340000  40.790001  41.330002  34.090000   
2019-12-31  49.139999  28.940001  32.950001  40.650002  41.150002  34.099998   

                   IVV  
Date                    
2019-12-24  322.929993  
2019-12-26  324.329987  
2019-12-27  325.190002  
2019-12-30  324.489990  
2019-12-31  323.559998

In [7]:
high.to_csv("high_all.csv")

In [14]:
A = [np.random.random((5, 5)) for i in range(4)]
A

[array([[0.4267342 , 0.81219159, 0.56746302, 0.75825871, 0.7819683 ],
        [0.21407481, 0.19350909, 0.01990262, 0.59158488, 0.9459837 ],
        [0.25717477, 0.7163765 , 0.05080794, 0.30853066, 0.48679922],
        [0.87925606, 0.18564638, 0.82358724, 0.12714297, 0.63126045],
        [0.13973565, 0.54367403, 0.96331283, 0.79357857, 0.4943064 ]]),
 array([[0.10309005, 0.76583193, 0.580282  , 0.56588115, 0.88101216],
        [0.7135149 , 0.0503772 , 0.19646094, 0.85297867, 0.77242469],
        [0.26568298, 0.52176159, 0.51825435, 0.97196632, 0.80991251],
        [0.73534042, 0.4109172 , 0.35021646, 0.85935455, 0.82042613],
        [0.9599049 , 0.67356128, 0.32702544, 0.97748691, 0.41408522]]),
 array([[0.3601228 , 0.03652344, 0.07746929, 0.83208626, 0.73473721],
        [0.11322123, 0.8580237 , 0.15428566, 0.8930267 , 0.24344104],
        [0.86085652, 0.32334672, 0.91626867, 0.09007031, 0.91433969],
        [0.94380947, 0.29821583, 0.20030235, 0.38466788, 0.38871985],
        [0.74535

In [6]:
low = pd.DataFrame()
tickers = ['EWA', 'EWZ', 'EWC', 'FXI', 'EWQ', 'EWG', 'EWH', 'EWI', 'EWJ', 'EWY',
           'EWN', 'EWS', 'EZA', 'EWP', 'EWD', 'EWL', 'EWT', 'EWU', 'IVV']
q = len(tickers)
records = 0
for i in tickers:
    tmp = web.DataReader(i, 'yahoo', '1/3/2005', '12/31/2019')   #1/3 is the first business day of 2005
    low[i] = tmp['Low']

low.head()

EWA        EWZ    EWC        FXI        EWQ    EWG    EWH  \
Date                                                                          
2005-01-03  16.469999  21.650000  17.01  18.373333  23.860001  18.49  11.98   
2005-01-04  16.120001  20.600000  16.57  17.860001  23.400000  18.10  11.68   
2005-01-05  16.200001  20.530001  16.40  17.443333  23.309999  18.09  11.42   
2005-01-06  16.129999  20.139999  16.25  17.366667  23.320000  18.08  11.50   
2005-01-07  16.150000  20.350000  16.15  17.266666  23.250000  18.00  11.37   

                  EWI        EWJ        EWY        EWN    EWS        EZA  \
Date                                                                       
2005-01-03  50.720001  43.160000  28.700001  18.389999  14.10  39.500000   
2005-01-04  49.759998  42.279999  28.049999  18.100000  13.76  38.525002   
2005-01-05  50.000000  42.320000  28.100000  18.049999  14.02  37.275002   
2005-01-06  49.700001  42.200001  27.750000  17.969999  14.12  36.294998   
2005-01-07  49.380001  42.160000  27.660000  17.860001  14.20  36.549999   

                  EWP        EWD        EWL        EWT        EWU         IVV  
Date                                                                           
2005-01-03  35.099998  21.000000  17.120001  23.740000  35.840000  120.029999  
2005-01-04  34.450001  20.600000  16.629999  23.020000  35.099998  118.559998  
2005-01-05  34.240002  20.530001  16.639999  22.940001  35.259998  118.290001  
2005-01-06  34.080002  20.500000  16.600000  22.900000  35.180000  118.449997  
2005-01-07  33.619999  20.280001  16.350000  22.799999  35.160000  118.330002

In [8]:
low.to_csv("low_all.csv")

In [19]:
from functools import reduce
product2 = reduce(np.dot, A)
product2

array([[14.76649882, 14.53989848, 13.89226599, 14.5393385 , 17.53186031],
       [ 8.91872269,  8.74627327,  8.25943045,  8.66726859, 10.56014249],
       [ 7.76626302,  7.66135221,  7.33004413,  7.64423263,  9.2458717 ],
       [12.10877689, 11.85898583, 11.24978584, 11.9050345 , 14.28397645],
       [13.11822975, 12.92323957, 12.3881326 , 12.95715614, 15.5644949 ]])

In [21]:
product1 = A[0].dot(A[1]).dot(A[2]).dot(A[3])
product1

array([[14.76649882, 14.53989848, 13.89226599, 14.5393385 , 17.53186031],
       [ 8.91872269,  8.74627327,  8.25943045,  8.66726859, 10.56014249],
       [ 7.76626302,  7.66135221,  7.33004413,  7.64423263,  9.2458717 ],
       [12.10877689, 11.85898583, 11.24978584, 11.9050345 , 14.28397645],
       [13.11822975, 12.92323957, 12.3881326 , 12.95715614, 15.5644949 ]])

In [30]:
product1*-1

array([[-14.76649882, -14.53989848, -13.89226599, -14.5393385 ,
        -17.53186031],
       [ -8.91872269,  -8.74627327,  -8.25943045,  -8.66726859,
        -10.56014249],
       [ -7.76626302,  -7.66135221,  -7.33004413,  -7.64423263,
         -9.2458717 ],
       [-12.10877689, -11.85898583, -11.24978584, -11.9050345 ,
        -14.28397645],
       [-13.11822975, -12.92323957, -12.3881326 , -12.95715614,
        -15.5644949 ]])

In [ ]:
matrixs = [A, B, C, D, E]
reduce(np.dot, matrixs)

In [ ]:
macd = pd.DataFrame(index = data.index)

long_bucket = []
short_bucket = []
for stk in tickers:
    # talib计算MACD
    macd_tmp = talib.MACD(data[stk].values, fastperiod=12, slowperiod=26, signalperiod=9)
    DIF = macd_tmp[0]
    DEA = macd_tmp[1]
    MACD = macd_tmp[2]
    print("DIF:", DIF)
    print("DEA:",DEA)
    print("MACD:",MACD)
    
    # 判断MACD走向
    if MACD[-1] > 0 and MACD[-4] < 0:
        long_bucket.append(stk)
    elif MACD[-1] < 0 and MACD[-4] > 0:
        short_bucket.append(stk)
    

print(long_bucket)
print(short_bucket)